version: "3"

volumes:
    postgres_data:
        driver: local

services:
    postgres:
        container_name: app_db
        image: postgis/postgis:14-3.1-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
